### ISSUE TITLE
Show passenger information to the driver

### ISSUE THREAD

**Issue by andrewnoyes** [unfrl/carpool#101]
When a user navs to the carpool page and they're a driver, pull the passenger list and display it in the collapsible details panel for that driver item.

I think it'd look nice if the passenger information was displayed in a [table](https://material-ui.com/components/tables/#table) component with the columns: Display name, Telephone, and Address.

**Comment by MattInternet** [comment]
After PR #149 the driver (and creator) should have this info, but theres no UI for it now. Assigning to @andrewnoyes
